name: Build and Publish gradle-confluent Plugin
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Release Plugin
      if: github.event_name == 'push'
      run: ./gradlew -Panalytics.buildTag=${{ github.sha }} cleanLibs release -Prelease.disableChecks -Prelease.localOnly -S
    - name: Build Plugin
      run: ./gradlew -Panalytics.buildTag=${{ github.sha }} build -S
    - name: Start Confluent
      run: ./gradlew -Panalytics.buildTag=${{ github.sha }} composeUp -q
    - name: Test Plugin
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: ./gradlew -Panalytics.buildTag=${{ github.sha }} runAllTests publishTestReports -S -PexecutionId=${{ github.sha }}
    - name: Publish Plugin
      if: github.event_name == 'push'
      run: ./gradlew -Panalytics.buildTag=${{ github.sha }} publishPlugins -S -PgithubToken=${{ secrets.GITHUB_TOKEN }}
